version: '3'
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - default
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  app:
    tty: true
    stdin_open: true
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - bundle:/app/vendor/bundle
    ports:
      - 3000:3000
    depends_on:
      - postgres
    environment:
      DB_NAME: graphql_development
      DB_USER: postgres
      DB_PASS: password
      DB_HOST: postgres
      DB_PORT: 5432
    command: ["bundle", "exec", "rails", "s", "-b", "0.0.0.0"]
volumes:
  postgres-data:
    driver: local
  bundle:
    driver: local